from random import choice
print('Digite o nome dos alunos')
al1 = input('Primeiro aluno:')
al2 = input('Segundo aluno:')
al3 = input('Terceiro aluno:')
al4 = input('Quarto aluno:')
al5 = input('Quinto Aluno:')
lista = (al1,al2,al3,al4,al5)
sor = choice(lista)
print('O aluno escolhido foi o {}'.format(sor))