algo = input('digite algo:')
tipo = (type(algo))
numero = (algo.isnumeric())
alfabeto = (algo.isalpha())
espaço = (algo.isspace())
alfanumerico = (algo.isalnum())
maiuscula = (algo.isupper())
minuscula = (algo.islower())
capitalizado = (algo.istitle())
print('Só tem espaços?', espaço)
print('É um numero?', numero)
print('É alfabetico?', alfabeto)
print('É Alfanumerico', alfanumerico)
print('Está em maiusculo?', maiuscula)
print('Está em minuscula?', minuscula)
print('Está capitalizado?', capitalizado)
